window.PORTFOLIO_DEFAULT_PROJECTS = [
    {
        id: "veggie-wash",
        title: "Veggie Wash",
        tagline: "Relaxing ASMR cleaning simulator with vegetables, upgrades, coins, and satisfying tactile feedback.",
        statusLabel: "Live on Google Play",
        statusType: "live",
        type: "ASMR Simulator",
        genre: "Washing Simulator",
        platform: "Android",
        role: "Solo Developer",
        focus: "Touch feel, progression, polish",
        logo: "veggie icon.png",
        cover: "vegie wash 1.jpg",
        linkUrl: "https://play.google.com/store/apps/details?id=com.CapbuuGames.VegieWash",
        linkLabel: "View on Google Play",
        summary: "A relaxing ASMR cleaning simulator where players wash vegetables, earn coins, upgrade tools, and unlock new produce through satisfying touch-based interactions.",
        overview: "The project focuses on a simple, understandable loop: dirty item, clean interaction, reward, upgrade, and unlock. Every touch is designed to feel useful while keeping sessions calm, clear, and mobile-friendly.",
        loop: "Wash vegetables, earn coins, improve tools, unlock new produce, and repeat with clear visual progress.",
        technical: "Unity gameplay systems, mobile input, animated object states, upgrade data, UI flow, Android builds, and store presentation.",
        signal: "Shows the ability to ship a complete casual mobile game from prototype to public store page.",
        screenshots: ["vegie wash 1.jpg", "veggie wash 2.jpg"],
        videos: []
    },
    {
        id: "coin-wood",
        title: "Coin Wood",
        tagline: "Fast arcade dodger with falling logs, apples, powerups, score pressure, and quick mobile restarts.",
        statusLabel: "Live on Google Play",
        statusType: "live",
        type: "Arcade Mobile Game",
        genre: "Infinite Dodger",
        platform: "Android",
        role: "Solo Developer",
        focus: "Input, hazards, replayability",
        logo: "coin wood pfp.png",
        cover: "coin wood 1.png",
        linkUrl: "https://play.google.com/store/apps/details?id=com.KitlerDev.Coinwood",
        linkLabel: "View on Google Play",
        summary: "An infinite arcade dodger built for quick mobile sessions, readable hazards, coin collection, powerups, and a clean one-more-run rhythm.",
        overview: "Coin Wood is built around fast threat recognition and immediate restart energy. The player dodges falling logs, collects apples, and uses powerups to extend runs without slowing down the core loop.",
        loop: "Dodge hazards, collect apples, trigger powerups, improve score, and restart quickly.",
        technical: "Spawn pacing, collision logic, scoring, powerups, mobile controls, UI states, and Android release flow.",
        signal: "Shows compact arcade design, feel tuning, and shipping discipline.",
        screenshots: ["coin wood 1.png", "coin wood 2.png"],
        videos: []
    },
    {
        id: "nebulo",
        title: "Nebulo",
        tagline: "Calm isometric adventure about floating platforms, fireflies, traversal, and peaceful puzzle spaces.",
        statusLabel: "In development",
        statusType: "progress",
        type: "Isometric Adventure",
        genre: "Puzzle Adventure",
        platform: "Mobile target",
        role: "Solo Developer",
        focus: "Atmosphere, movement, puzzles",
        logo: "nebulo icon.png",
        cover: "nebulo 1.png",
        linkUrl: "",
        linkLabel: "Discuss the project",
        summary: "A calm isometric adventure about jumping across floating platforms, waking fireflies, and exploring a soft atmospheric world.",
        overview: "Nebulo explores soft pacing, clean isometric composition, gentle challenge, and progression that feels like discovery instead of pressure.",
        loop: "Move across platforms, solve gentle traversal beats, wake fireflies, and progress through floating spaces.",
        technical: "Isometric presentation, platform logic, scene art direction, camera framing, and mobile interaction tests.",
        signal: "Shows range in atmosphere, pacing, and environmental game feel.",
        screenshots: ["nebulo 1.png", "nebulo 2.png"],
        videos: []
    },
    {
        id: "scrap-race",
        title: "Scrap Race",
        tagline: "Truck collection simulator with routes, scrap recycling, missions, upgrades, and tycoon-style growth.",
        statusLabel: "Closed testing",
        statusType: "testing",
        type: "Truck Simulator",
        genre: "Simulator",
        platform: "Android target",
        role: "Solo Developer",
        focus: "Missions, upgrades, economy",
        logo: "scrap race logo.png",
        cover: "scrap race.png",
        linkUrl: "",
        linkLabel: "Ask about testing",
        summary: "A truck collection simulator about driving routes, gathering scrap waste, recycling for cash, completing missions, and upgrading a cleanup vehicle.",
        overview: "Scrap Race combines vehicle movement, resource collection, and upgrade goals. The player reads the route, collects waste, converts it into cash, and uses rewards to improve the truck and complete better missions.",
        loop: "Drive, collect scrap, recycle for cash, complete missions, upgrade the truck, and scale the route.",
        technical: "Vehicle control, item collection, mission tracking, reward economy, upgrade states, and testing builds.",
        signal: "Shows ability to build layered simulation systems with mobile-friendly clarity.",
        screenshots: ["scrap race.png", "scrap race 2.png", "scrap race logo.png"],
        videos: []
    },
    {
        id: "usm",
        title: "USM - Universal Sound Manager",
        tagline: "Unity audio workflow tool with one-line playback, editor setup, multi-track composition, and reusable controls.",
        statusLabel: "Unity Asset Store",
        statusType: "live",
        type: "Unity Tool",
        genre: "Audio Tool",
        platform: "Unity Asset Store",
        role: "Tool Creator",
        focus: "Audio workflow, API, editor UX",
        logo: "logo.png",
        cover: "usm 3.png",
        linkUrl: "https://assetstore.unity.com/packages/tools/audio/usm-universal-sound-manager-331090",
        linkLabel: "View on Asset Store",
        summary: "A Unity audio workflow tool that simplifies playback, editor setup, multi-track timeline composition, and reusable sound control for developers.",
        overview: "USM reduces repetitive audio code with simple playback calls, visual editor controls, timeline-style composition, and reusable configuration patterns.",
        loop: "Register sounds, organize audio, trigger playback, layer tracks, and adjust behavior in editor tools.",
        technical: "Unity editor scripting, API design, serialized data, audio playback systems, documentation, and packaging.",
        signal: "Shows tool-building ability beyond games, with attention to developer experience.",
        screenshots: ["usm 3.png", "audio editor 2.png"],
        videos: []
    }
];
